name: functional testing

on: [push, pull_request]

env:
  CI: 1
  GCS_UPLOAD_PREFIX: fake
  TEST_OPENSEARCH_DASHBOARDS_HOST: localhost
  TEST_OPENSEARCH_DASHBOARDS_PORT: 6610
  TEST_OPENSEARCH_TRANSPORT_PORT: 9403
  TEST_OPENSEARCH_PORT: 9400
  OSD_SNAPSHOT_SKIP_VERIFY_CHECKSUM: true

jobs:
  test:
    name: Functional tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout plugin source code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          path: bitergia-analytics-plugin
      - name: Get plugin metadata
        id: plugin_metadata
        run: |
          echo "name=$(node -p "(require('./bitergia-analytics-plugin/package.json').name)")" >> $GITHUB_OUTPUT
          echo "version=$(node -p "(require('./bitergia-analytics-plugin/package.json').version).match(/[.0-9]+/)[0]")" >> $GITHUB_OUTPUT
      - name: Get OpenSearch Dashboards version
        id: osd_version
        run: |
          echo "version=$(node -p "(require('./bitergia-analytics-plugin/opensearch_dashboards.json').opensearchDashboardsVersion).match(/[.0-9]+/)[0]")" >> $GITHUB_OUTPUT
      - name: Checkout OpenSearch Dashboards
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          repository: opensearch-project/OpenSearch-Dashboards
          ref: ${{ steps.osd_version.outputs.version }}
          path: OpenSearch-Dashboards
      - name: Get node and yarn versions
        id: versions
        run: |
          echo "node_version=$(node -p "(require('./OpenSearch-Dashboards/package.json').engines.node).match(/[.0-9]+/)[0]")" >> $GITHUB_OUTPUT
          echo "yarn_version=$(node -p "require('./OpenSearch-Dashboards/package.json').engines.yarn")" >> $GITHUB_OUTPUT
      - name: Setup node
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # 4.0.1
        with:
          node-version: ${{ steps.versions.outputs.node_version }}
      - name: Setup yarn
        run: |
          npm uninstall -g yarn
          echo "Installing yarn ${{ steps.versions_step.outputs.yarn_version }}"
          npm i -g yarn@${{ steps.versions.outputs.yarn_version }}
      - name: Move plugin to OpenSearch Dashboards folder
        run: |
          mkdir -p OpenSearch-Dashboards/plugins
          mv bitergia-analytics-plugin OpenSearch-Dashboards/plugins
      - name: Bootstrap plugin/opensearch-dashboards
        run: |
          cd OpenSearch-Dashboards/plugins/bitergia-analytics-plugin
          yarn osd bootstrap
      - name: Run functional tests
        run: |
          cd ./OpenSearch-Dashboards/plugins/bitergia-analytics-plugin
          yarn test:api
